### PR TITLE
Unselect points and rects when init is executed with false value

### PR DESCRIPTION
**Pull request by Hugoer**
If i am working with deepselect: true, when i select a polygon it works correctly, but when i try to "unselect" ( selectize(false) ), the array of points to drag polygon points they are not deleted.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Does `selectize(false, {deepSelect: true})` not work?

**Comment by Hugoer** [comment]
Hi Fuzzyma! No, it doesn´t work. I try to select with:

            .selectize()
            .selectize({
                deepSelect: true,
            })
and with
            .selectize()
            .selectize(true, {
                deepSelect: true,
            })

and unselect with your suggestion. but it doesn´t work. With your comment, the rect of bbox still persists. It could be another combination of options, but i watched the code and i didn´t find it. If you need it, i can create a stackblitz to show what i am doing and test it.

**Comment by Fuzzyma** [comment]
When you select with both you also have to unselect with both.
So:

```js
        .selectize(fakse)
        .selectize(false, {
            deepSelect: true,
        })
```

**Comment by Hugoer** [comment]
Yes! it works! Sorry for wasting your time and lot of thanks for the support 👍  reject the pull request

**Pull request closed without merging**
