### PR TITLE
ES6/Typescript update for v3

### PR DESCRIPTION
**Pull request by adaliszk**
- Added Typescript types
- Moved SelectHandler into a separate file
- Exported the handler with ES6
- Typehinted the .selectize() method
- Removed old code (git will have the history)

The idea is to split up the code a little in-case someone - like me - would like to extend the base class and modify some of the behaviors in a subpackage.

### CODE REVIEW

**Comment by Fuzzyma** [comment]
Uh cool, you found the branch with the new code :D.
It wasn't released because the resize-plugin which relies on select wasn't ready yet.
Also, I didn't decide yet how I want resizing to happen (coordinate changes vs transformations - at the moment its a mixture of both).

But yeah -- that's unrelated to this PR. Thanks for your work :)

**Comment by adaliszk** [comment]
Your welcome, I hopefully will able to share a bit more later.
By the way, is there room to move the code to typescript?
Also, what are the missing features you need?

**Comment by adaliszk** [comment]
some tickets should be better with the merge:
/related #33 
/related #61

**Comment by Fuzzyma** [comment]
Since whole svg.js is not written in typescript imo it makes not too much sense to have the plug-ins use typescript as it will confuse people. Also: especially for the Plug-ins I don't really see the benefit because they are mostly small and easy to manage.

For the features I am not too sure either.
The thing is most big graphic programs distinguish between resizing and transforming shapes and I see the benefit in doing so. Also manipulating the shape itself (by e. G. changing points in a poly line) is actually a separate thing. So I feel like at some point we have to have multiple selection modes each for a different form of editing.

- resizing for changing width and height in untransformed state
- transforming (= scaling, rotating, skewing, translating)
- manipulation where the actual shape data is manipulated (= editing single points in poly line or paths)

Bonus points for making it possible to reuse the same code for all this + drawing the shape :D

**Comment by adaliszk** [comment]
Hmm, the possible confusion is a great point, though I feel like the whole project could benefit a lot with typescript and the plugins are small enough to start. To be honest, it just ugly when you extend an ES6 class:
image
Maybe I can fix it by adding the type declarations.

I agree on the particular plugin modules and the way to extend it, from my viewpoint the main use-cases are already there for a Graphical Editor project, hopefully, I will able to share more later, we are in an early experimental phase at the moment.

What I actually need is extending the already exist classes and define my own handle UI. What's kinda buggy is using multiple plugins together as they sometimes fail to behave with each other. I've ended up having a monorepo where I collect the plugins into their own space and edit them together.

**Comment by Fuzzyma** [comment]
The plugins draw, resize, select and draggable were actually all written more or less together but ofc screw-ups happen :D.
For the typescript: We actually have pretty decent typings for svg.js and the updated plugins so working with them should actually be a pretty pleasant experience

> from my viewpoint the main use-cases are already there for a Graphical Editor project

Yes and No. Yes, you can do a lot of stuff but it kinda feels a bit mixed up. Especially resizing and rotating together

**Pull request merged**
